site_name: OpenMAS
site_url: https://docs.openmas.ai/
repo_url: https://github.com/openmas-ai/openmas
repo_name: openmas-ai/openmas

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: custom # Uses colors defined in extra.css
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom # Uses colors defined in extra.css
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Why OpenMAS?: why_openmas.md
  - Core Concepts:
      - Design Philosophy: core_concepts/design.md
      - Architecture: core_concepts/architecture.md
      - Project Structure: core_concepts/project_structure.md
  - Guides:
      - Installation: guides/installation.md
      - Getting Started: guides/getting_started.md
      - Configuration: guides/configuration.md
      - Deployment: guides/deployment.md
      - Communication:
        - Overview: guides/communication/index.md
        - Message Patterns: guides/communication/message_patterns.md
        - Request-Response: guides/communication/request_response.md
        - Command-Response: guides/communication/command_response.md
        - Broadcast: guides/communication/broadcast.md
      - LLM Integration: guides/llm_integration.md
      - Prompt Management: guides/prompt_management.md
      - Sampling Configuration: guides/sampling_configuration.md
      - Asset Management: guides/asset_management.md
      - Reasoning Integration: guides/reasoning_integration.md
      - Patterns: guides/patterns.md
      - MCP Developer Guide: guides/mcp_developer_guide.md
      - MCP SSE Tool Call Tutorial: guides/mcp_sse_tool_call_tutorial.md
      - MCP Integration: guides/mcp_integration.md
      - MCP stdio Tool Call Tutorial: guides/mcp_stdio_tool_call_tutorial.md
      - Testing Utilities: guides/testing-utilities.md
  - Examples & Use Cases:
      - Overview: examples.md
      - Chesspal.ai Refactoring: use_cases/chesspal_ai.md
  - Extending OpenMAS:
      - Custom Communicators: communicator_extensions.md
      # - Custom Agent Patterns: # Placeholder
      # - Custom Reasoning: # Placeholder
  - Command Line Interface:
      - Overview: cli/index.md
      - init: cli/init.md
      - validate: cli/validate.md
      - list: cli/list.md
      - run: cli/run.md
      - deps: cli/deps.md
      - generate-dockerfile: cli/generate-dockerfile.md
      - generate-compose: cli/generate-compose.md
      - assets: cli/assets.md
      - prompts: cli/prompts.md
  - Contributing:
      - Guidelines: contributing/contributing.md
      - Testing: contributing/testing_strategy.md
      - Development Workflow: contributing/development_workflow.md
      - Docstring Policy: contributing/docstring_policy.md
      - Example Prompts: contributing/example_prompts.md
      - Prompt & Sampling Implementation: contributing/prompt_and_sampling.md
  - API Reference: api_reference.md
  - OpenMAS Home: https://www.openmas.ai/

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]  # Look for modules in the src directory
          options:
            show_source: true
            # members_order: source # Optional: Order members as they appear in source
            # show_root_heading: true # Optional
            # heading_level: 2 # Optional

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css # Removed version query string for simplicity
