site_name: OpenMAS
site_url: https://docs.openmas.ai
repo_url: https://github.com/openmas-ai/openmas
repo_name: openmas-ai/openmas

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: custom # Uses colors defined in extra.css
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom # Uses colors defined in extra.css
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Guides:
      - Installation: guides/installation.md
      - Getting Started: guides/getting_started.md
      - Configuration: guides/configuration.md
      - Communication: guides/communication.md
      - LLM Integration: guides/llm_integration.md
      - MCP Integration: guides/mcp_integration.md
      - Reasoning Integration (BDI): guides/reasoning_integration.md
      - Agent Patterns: guides/patterns.md
      - Testing Your Agents: guides/testing-utilities.md
      - Deployment: guides/deployment.md
  - Core Concepts:
      - Architecture: architecture.md
      - Design Philosophy: design.md
      - Project Structure: project_structure.md # Added here
  - Examples & Use Cases: # Added section
      - Overview: examples.md # Added
      - Chesspal.ai Refactoring: use_cases/chesspal_ai.md # Added
  - Extending OpenMAS:
      - Custom Communicators: communicator_extensions.md
      # - Custom Agent Patterns: # Placeholder
      # - Custom Reasoning: # Placeholder
  - Command Line Interface:
      - Overview: cli/index.md
      - init: cli/init.md
      - validate: cli/validate.md
      - list: cli/list.md
      - run: cli/run.md
      - deps: cli/deps.md
      - generate-dockerfile: cli/generate-dockerfile.md
      - generate-compose: cli/generate-compose.md # Added
  - Contributing:
      - Guidelines: contributing.md
      - Development Workflow: development_workflow.md
      - Docstring Policy: docstring_policy.md
  - API Reference: api_reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]  # Look for modules in the src directory
          options:
            show_source: true
            # members_order: source # Optional: Order members as they appear in source
            # show_root_heading: true # Optional
            # heading_level: 2 # Optional

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css # Removed version query string for simplicity
