# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import simple_mas_pb2 as simple__mas__pb2

GRPC_GENERATED_VERSION = "1.72.0rc1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in simple_mas_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SimpleMasServiceStub(object):
    """Generic message structure for SimpleMas communications"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRequest = channel.unary_unary(
            "/simple_mas.SimpleMasService/SendRequest",
            request_serializer=simple__mas__pb2.RequestMessage.SerializeToString,
            response_deserializer=simple__mas__pb2.ResponseMessage.FromString,
            _registered_method=True,
        )
        self.SendNotification = channel.unary_unary(
            "/simple_mas.SimpleMasService/SendNotification",
            request_serializer=simple__mas__pb2.NotificationMessage.SerializeToString,
            response_deserializer=simple__mas__pb2.Empty.FromString,
            _registered_method=True,
        )


class SimpleMasServiceServicer(object):
    """Generic message structure for SimpleMas communications"""

    def SendRequest(self, request, context):
        """Send a request and receive a response"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendNotification(self, request, context):
        """Send a notification without expecting a response"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SimpleMasServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendRequest": grpc.unary_unary_rpc_method_handler(
            servicer.SendRequest,
            request_deserializer=simple__mas__pb2.RequestMessage.FromString,
            response_serializer=simple__mas__pb2.ResponseMessage.SerializeToString,
        ),
        "SendNotification": grpc.unary_unary_rpc_method_handler(
            servicer.SendNotification,
            request_deserializer=simple__mas__pb2.NotificationMessage.FromString,
            response_serializer=simple__mas__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("simple_mas.SimpleMasService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("simple_mas.SimpleMasService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SimpleMasService(object):
    """Generic message structure for SimpleMas communications"""

    @staticmethod
    def SendRequest(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/simple_mas.SimpleMasService/SendRequest",
            simple__mas__pb2.RequestMessage.SerializeToString,
            simple__mas__pb2.ResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SendNotification(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/simple_mas.SimpleMasService/SendNotification",
            simple__mas__pb2.NotificationMessage.SerializeToString,
            simple__mas__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
