version: '3'

services:
  mcp-server:
    build:
      context: ..
      dockerfile: examples/Dockerfile
    command: python -m examples.mcp_agent
    environment:
      - AGENT_NAME=chess-mcp-server
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"

  http-agent:
    build:
      context: ..
      dockerfile: examples/Dockerfile
    command: python -m examples.simple_agent
    environment:
      - AGENT_NAME=simple-agent
      - LOG_LEVEL=INFO
      - SERVICE_URL_MCP_SERVER=http://mcp-server:8000
    depends_on:
      - mcp-server

  mcp-client:
    build:
      context: ..
      dockerfile: examples/Dockerfile
    command: python -m examples.mcp_client
    environment:
      - AGENT_NAME=chess-client
      - LOG_LEVEL=INFO
      - MCP_SERVER_URL=http://mcp-server:8000
    depends_on:
      - mcp-server
