version: '3'
services:
  chess-player:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - AGENT_NAME=chess-player
    - LOG_LEVEL=INFO
    - COMMUNICATOR_TYPE=mcp_stdio
    - 'COMMUNICATOR_OPTIONS={"model": "claude-3-opus-20240229"}'
    - MCP_API_KEY
    - SERVICE_URL_MCP_SERVER=http://mcp-server:8000
    - SERVICE_URL_GAME_COORDINATOR=http://game-coordinator:8002
    ports:
    - 8000:8000
    - 8001:8001
    volumes:
    - ./chess-memory:/app/data/memory
    - ./logs:/app/logs
    depends_on:
    - mcp-server
    - game-coordinator
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8000/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
